name: Go CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    # Cache Go dependencies
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Build the project
    - name: Build
      run: go build -v ./...

    # Run tests
    - name: Test
      run: go test -v ./...

  save-artifacts:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
    # Checkout code again if necessary
    - name: Checkout code
      uses: actions/checkout@v4

    # Save binary artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: sisyphus
        path: ./sisyphus
